### ISSUE TITLE
请问您这个是不是没有调用fastdfs提供的PHP接口，全部都是自己写的操作？

### ISSUE THREAD

**Issue by zurmokeeper** [qpwoeiru96/PHP-FastDFS-Client#2]
请问您这个是不是没有调用fastdfs提供的PHP接口，全部都是自己写的操作？

**Comment by qpwoeiru96** [comment]
不明白你说的是什么，能否具体描述一下。

**Comment by zurmokeeper** [comment]
FastDFS官方提供了一个PHP的API用来一些基本的CURD操作，可是我看您的代码里好像并没有调用这些API，您是自己写API来操作文件的嘛？我的意思就是这样的。

**Comment by qpwoeiru96** [comment]
对对。我这个版本的Client是原生php通过socket与FastDFS服务端直接进行交互，没有使用fastdfs里面的c api。主要是方便在windows使用fastdfs的服务。
